CREATE TABLE Cliente (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  cpf INTEGER UNSIGNED NOT NULL,
  email VARCHAR(50) NOT NULL,
  senha VARCHAR(50) NOT NULL,
  telefone INTEGER UNSIGNED NOT NULL,
  endereco VARCHAR(80) NOT NULL,
  pergunta_secreta VARCHAR(50) NOT NULL,
  resposta_secreta VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE Compra (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  data_compra DATE NULL,
  total_compra FLOAT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE Categoria (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NULL,
  descricao TEXT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE Admin (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NULL,
  email VARCHAR(50) NULL,
  senha INTEGER UNSIGNED NULL,
  PRIMARY KEY(id)
);

CREATE TABLE Produto (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Categoria_id INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(50) NULL,
  descricao TEXT NULL,
  valor FLOAT NULL,
  flag_destaque_promocao BOOL NULL,
  url_miniatura TEXT NULL,
  url_foto TEXT NULL,
  fabricante VARCHAR(50) NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(Categoria_id)
    REFERENCES Categoria(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Produto_Compra (
  Produto_id INTEGER UNSIGNED NOT NULL,
  Compra_id INTEGER UNSIGNED NOT NULL,
  quantidade INTEGER UNSIGNED NULL,
  valor_total FLOAT NULL,
  PRIMARY KEY(Produto_id, Compra_id),
  FOREIGN KEY(Produto_id)
    REFERENCES Produto(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Compra_id)
    REFERENCES Compra(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Cliente_Compra (
  Cliente_id INTEGER UNSIGNED NOT NULL,
  Compra_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(Cliente_id, Compra_id),
  FOREIGN KEY(Cliente_id)
    REFERENCES Cliente(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Compra_id)
    REFERENCES Compra(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Boleto (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Compra_id INTEGER UNSIGNED NOT NULL,
  Cliente_id INTEGER UNSIGNED NOT NULL,
  flag_pagamento BOOL NULL,
  valor FLOAT NULL,
  data_gerado DATE NULL,
  data_vencimento DATE NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(Cliente_id)
    REFERENCES Cliente(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Compra_id)
    REFERENCES Compra(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);
